/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyectoudaleku.Main;

/**
 *
 * @author 1glm07
 */
public class panInicio extends javax.swing.JPanel {

    /**
     * Creates new form panInicio
     */
    public panInicio() {
        initComponents();
        lAraba.setVisible(false);lBizkaia.setVisible(false);lGipuzkoa.setVisible(false);
        JOptionPane.showMessageDialog(null, "Elige desde qué provincia quieres hacer los trámites");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bBizkaia = new javax.swing.JButton();
        bAraba = new javax.swing.JButton();
        bGipuzkoa = new javax.swing.JButton();
        lAraba = new javax.swing.JLabel();
        lGipuzkoa = new javax.swing.JLabel();
        lBizkaia = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(1300, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udalekuak_inicio.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chavales1.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chavales2.jpg"))); // NOI18N

        bBizkaia.setText("BIZKAIA");
        bBizkaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBizkaiaActionPerformed(evt);
            }
        });

        bAraba.setText("ARABA");
        bAraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArabaActionPerformed(evt);
            }
        });

        bGipuzkoa.setText("GIPUZKOA");
        bGipuzkoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGipuzkoaActionPerformed(evt);
            }
        });

        lAraba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diputacion_araba.jpg"))); // NOI18N

        lGipuzkoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diputacion_gipuzkoa.jpg"))); // NOI18N

        lBizkaia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diputacion_bizkaia.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bBizkaia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bAraba, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bGipuzkoa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(lAraba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lGipuzkoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lBizkaia, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bAraba, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bBizkaia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bGipuzkoa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAraba, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lGipuzkoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBizkaia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bArabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArabaActionPerformed
        lAraba.setVisible(true);lBizkaia.setVisible(false); lGipuzkoa.setVisible(false);

        Main.setProvincia("ARB");

        Main.getProvSelected().setNombreprov("ARB");

    }//GEN-LAST:event_bArabaActionPerformed

    private void bBizkaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBizkaiaActionPerformed
        lBizkaia.setVisible(true);lAraba.setVisible(false); lGipuzkoa.setVisible(false);

        Main.setProvincia("BZK");

        Main.getProvSelected().setNombreprov("BZK");

    }//GEN-LAST:event_bBizkaiaActionPerformed

    private void bGipuzkoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGipuzkoaActionPerformed
        lGipuzkoa.setVisible(true);lBizkaia.setVisible(false); lAraba.setVisible(false);

        Main.setProvincia("GZK");

        Main.getProvSelected().setNombreprov("GZK");

    }//GEN-LAST:event_bGipuzkoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAraba;
    private javax.swing.JButton bBizkaia;
    private javax.swing.JButton bGipuzkoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lAraba;
    private javax.swing.JLabel lBizkaia;
    private javax.swing.JLabel lGipuzkoa;
    // End of variables declaration//GEN-END:variables
}
